Repository retaildevcrews/helium-csharp, pull requests merged in 2020-03, with the labels that each got.

#59 created common query function, replaced calls in Actor and Movie, del…
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
Labels: C#, size: S

#61 remove reference to azure Dev Ops and Azure Pipelines
  README.md
Labels: C#, Documentation, Pri 1, size: S

#60 C# - Swagger Updates
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.old
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ParameterValidator.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/helium.csproj
  src/app/wwwroot/swagger/helium/swagger.json
  src/unit-tests/ActorsTest.cs
  src/unit-tests/MockDal.cs
  src/unit-tests/MoviesTest.cs
Labels: C#

#62 Key Vault Parameters
  .github/ISSUE_TEMPLATE/comparison.md
  CHANGELOG.md
  README.md
  src/app/Constants.cs
  src/app/GlobalSuppressions.cs
  src/app/Program.cs
  src/app/helium.csproj
  src/app/wwwroot/swagger.json
  src/unit-tests.sln
  src/unit-tests/ParamTest.cs
Labels: C#

#63 Updated to use Semantic Versioning
  src/app/Constants.cs
  src/app/Version.cs
  src/app/helium.csproj
  src/app/wwwroot/swagger.json
Labels: C#

#64 Update results ordering
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMovies.cs
Labels: C#

#65 C# refactor
  .github/workflows/dockerByPR.yml
  Dockerfile
  Dockerfile-Dev
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ParameterValidator.cs
  src/app/Controllers/ResultHandler.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/HealthChecks/HealthzCheck.cs
  src/app/HealthChecks/IetfCheck.cs
  src/app/Middleware/RequestLogger/LoggerMiddlewareExtensions.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/RequestLogger/loggerOptions.cs
  src/app/Middleware/indexHandler.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/version.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/Version.cs
  src/app/helium.csproj
  src/e2e-tests.sln
  src/tests/AssertValues.cs
  src/tests/ParamTest.cs
  src/tests/RunApp.cs
  src/tests/e2e-tests.csproj
  src/tests/test.cmd
  src/unit-tests/ActorsTest.cs
  src/unit-tests/MockDal.cs
  src/unit-tests/MoviesTest.cs
Labels: C#, Refactor

#69 Convert docker to alpine
  .github/workflows/dockerCI.yaml
  Dockerfile
Labels: C#
