Repository retaildevcrews/helium-csharp, pull requests merged in 2020-04, with the labels that each got.

#70 Command Line Processing
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ParameterValidator.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/KeyVault.Extensions/KeyVaultHelper.cs
  src/app/Program.cs
  src/app/helium.csproj
  src/tests.sln
  src/tests/ParamTest.cs
  src/tests/RunApp.cs
  src/tests/test.cmd
  src/tests/tests.csproj
  src/unit-tests.sln
  src/unit-tests/ActorsTest.cs
  src/unit-tests/AssertValues.cs
  src/unit-tests/FeaturedTest.cs
  src/unit-tests/GenresTest.cs
  src/unit-tests/MockDal.cs
  src/unit-tests/MoviesTest.cs
  src/unit-tests/ParamTest.cs
  src/unit-tests/data/actors.json
  src/unit-tests/data/featured.json
  src/unit-tests/data/genres.json
  src/unit-tests/data/movies.json
  src/unit-tests/unit-tests.csproj
Labels: C#

#71 updated healthz test
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
Labels: C#

#72 fixed --dry-run bug
  src/app/Program.cs
Labels: C#

#73 Refactor bluebell
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/task.md
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/version.cs
  src/app/Program.cs
  src/app/helium.csproj
Labels: C#

#74 add workflow for issue triage and PR submitted automation
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
Labels: C#, Pri 1, size: S

#75 Sql injection param protection
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/helium.csproj
Labels: C#, Pri 1, size: M

#80 Add --log-level support
  src/app/Constants.cs
  src/app/Middleware/RequestLogger/loggerOptions.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/helium.csproj
  src/tests/ParamTest.cs
Labels: C#

#81 updated readme
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: C#, Documentation, Release

#83 Updated namespace to CSE.Helium
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ParameterValidator.cs
  src/app/Controllers/ResultHandler.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/DalExtension.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/HealthChecks/HealthzCheck.cs
  src/app/HealthChecks/IetfCheck.cs
  src/app/HealthChecks/IetfResponseWriter.cs
  src/app/HealthChecks/JsonResponseWriter.cs
  src/app/HealthChecks/TimeSpanConverter.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Model/Actor.cs
  src/app/Model/FeaturedMovie.cs
  src/app/Model/Movie.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/helium.csproj
  src/tests/AssertValues.cs
  src/tests/ParamTest.cs
  src/tests/RunApp.cs
  src/tests/tests.csproj
Labels: C#
