Repository retaildevcrews/helium-csharp, pull requests merged in 2020-10, with the labels that each got.

#153 updated webv tests
  TestFiles/bad.json
  TestFiles/e2e.json
Labels: C#

#154 Added build args
  .github/workflows/dockerCI.yaml
  Dockerfile
  src/app/helium.csproj
Labels: C#

#152 Issue #151 update paths in dockerfile to fix codespaces build
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/docker-debian.sh
Labels: Bug, C#, CI/CD

#155 Enabled Stylecop
  src/.editorconfig
  src/app/CSE.KeyVault/AuthenticationType.cs
  src/app/CSE.KeyVault/KeyVaultConnection.cs
  src/app/CSE.KeyVault/KeyVaultConnectionExtension.cs
  src/app/CSE.KeyVault/KeyVaultHelper.cs
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ResultHandler.cs
  src/app/DataAccessLayer/DalExtension.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/Extensions/ActorExtensions.cs
  src/app/Extensions/MovieExtensions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/HealthChecks/HealthzCheck.cs
  src/app/HealthChecks/IetfResponseWriter.cs
  src/app/HealthChecks/TimeSpanConverter.cs
  src/app/Middleware/RequestLogger/LoggerMiddlewareExtensions.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/root.cs
  src/app/Middleware/version.cs
  src/app/Model/Actor.cs
  src/app/Model/Movie.cs
  src/app/Program.cs
  src/app/ServiceActivator.cs
  src/app/Startup.cs
  src/app/Validation/IdValidation.cs
  src/app/Validation/IntegerRangeValidation.cs
  src/app/Validation/ValidationProblemDetailsResult.cs
  src/app/Validation/YearValidation.cs
  src/app/helium.csproj
  src/helium.sln
  src/tests/tests.csproj
Labels: C#

#157 added copyright info
  src/.editorconfig
  src/app/CSE.KeyVault/AuthenticationType.cs
  src/app/CSE.KeyVault/IKeyVaultConnection.cs
  src/app/CSE.KeyVault/KeyVaultConnection.cs
  src/app/CSE.KeyVault/KeyVaultConnectionExtension.cs
  src/app/CSE.KeyVault/KeyVaultHelper.cs
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ResultHandler.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/DalExtension.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/Extensions/ActorExtensions.cs
  src/app/Extensions/MovieExtensions.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/HealthChecks/HealthzCheck.cs
  src/app/HealthChecks/IetfCheck.cs
  src/app/HealthChecks/IetfResponseWriter.cs
  src/app/HealthChecks/TimeSpanConverter.cs
  src/app/Middleware/RequestLogger/LoggerMiddlewareExtensions.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/RequestLogger/loggerOptions.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/root.cs
  src/app/Middleware/version.cs
  src/app/Model/Actor.cs
  src/app/Model/FeaturedMovie.cs
  src/app/Model/Movie.cs
  src/app/Program.cs
  src/app/QueryParameters.cs
  src/app/ServiceActivator.cs
  src/app/Startup.cs
  src/app/Validation/IdValidation.cs
  src/app/Validation/IntegerRangeValidation.cs
  src/app/Validation/ValidationProblemDetails.cs
  src/app/Validation/ValidationProblemDetailsResult.cs
  src/app/Validation/YearValidation.cs
  src/app/ValidationError.cs
  src/app/helium.csproj
  src/app/stylecop.json
Labels: C#

#141 Key rotation Issue#140
  src/app/CSE.KeyRotation/IKeyRotation.cs
  src/app/CSE.KeyRotation/KeyRotationExtension.cs
  src/app/CSE.KeyRotation/KeyRotationHelper.cs
  src/app/Constants.cs
  src/app/Controllers/GenresController.cs
  src/app/Program.cs
  src/app/helium.csproj
Labels: C#, CustomerFeedback

#158 resolved style cop issues
  src/.editorconfig
  src/app/CSE.KeyRotation/KeyRotationHelper.cs
  src/app/CSE.KeyVault/KeyVaultHelper.cs
  src/app/CommandLine.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/ErrorResult.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/QueryParameters/ActorIdParameter.cs
  src/app/Controllers/QueryParameters/ActorQueryParameters.cs
  src/app/Controllers/QueryParameters/MovieIdParameter.cs
  src/app/Controllers/QueryParameters/MovieQueryParameters.cs
  src/app/Controllers/QueryParameters/QueryParameters.cs
  src/app/Controllers/ResultHandler.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/DataAccessLayerExtension.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/Extensions/ActorExtensions.cs
  src/app/Extensions/MovieExtensions.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/HealthChecks/HealthzCheck.cs
  src/app/HealthChecks/IetfCheck.cs
  src/app/HealthChecks/IetfResponseWriter.cs
  src/app/Middleware/RequestLogger/LoggerExtension.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/RobotsExtension.cs
  src/app/Middleware/SwaggerRootExtension.cs
  src/app/Middleware/VersionExtension.cs
  src/app/Model/Actor.cs
  src/app/Model/ActorMovie.cs
  src/app/Model/Movie.cs
  src/app/Model/Role.cs
  src/app/Program.cs
  src/app/QueryParameters.cs
  src/app/ServiceActivator.cs
  src/app/Startup.cs
  src/app/Validation/ValidationProblemDetailsResult.cs
  src/app/ValidationError.cs
  src/app/stylecop.json
Labels: C#

#161 Fix 400 error resp link headers
  TestFiles/bad.json
  TestFiles/baseline.json
  TestFiles/e2e.json
  src/app/Validation/ValidationProblemDetailsResult.cs
Labels: C#
