Repository retaildevcrews/helium-csharp, pull requests merged in 2020-02, with the labels that each got.

#45 Sync github Templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: C#, Documentation

#46 GetGenreAsync bug fix
  src/app/Controllers/MoviesController.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
Labels: Bug, C#

#47 Fix fxcop issues
  .github/ISSUE_TEMPLATE/designreview.md
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/FeaturedController.cs
  src/app/Controllers/GenresController.cs
  src/app/Controllers/HealthzController.cs
  src/app/Controllers/MoviesController.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalGenres.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/helium.csproj
Labels: Bug, C#

#56 Updated Standard Templates (Bug, Task, Release, DoD, Feature)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/task.md
Labels: C#, Documentation, Pri 1

#57 Update CI fields and add badge to README
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.old
  .github/workflows/dockerCI.yaml
  README.md
  azure-pipelines.yml
Labels: C#, Enhancement, Pri 1, size: S
