Repository retaildevcrews/helium-csharp, pull requests merged in 2020-09, with the labels that each got.

#121 Added markdown file link check to CI
  .github/ISSUE_TEMPLATE/user-story.md
  .github/workflows/mdlinkcheck.yml
  README.md
  mlc_config.json
Labels: Bug, Documentation

#125 Experimentation ci-cd
  .github/workflows/experimentalCI.yaml
  Dockerfile
  src/app/Middleware/version.cs
  src/app/helium.csproj
  src/helium.sln
  src/tests/runtests
Labels: C#

#126 add language to /version
  .github/workflows/experimentalCI.txt
  TestFiles/baseline.json
  src/app/Controllers/ResultHandler.cs
  src/app/Middleware/version.cs
  src/app/Model/Actor.cs
Labels: C#

#130 Added scheduled markdown link check to CI
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, Documentation

#131 updated nuget packages and resolved new fxcop warnings
  src/app/CommandLine.cs
  src/app/DataAccessLayer/CosmosConfig.cs
  src/app/DataAccessLayer/dalMain.cs
  src/app/HealthChecks/CosmosHealthCheck.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/version.cs
  src/app/Program.cs
  src/app/helium.csproj
  src/tests/tests.csproj
Labels: C#

#134 --log-level bug fix
  .gitignore
  Dockerfile
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/appsettings.Development.json
  src/app/appsettings.json
Labels: C#, customer feedback

#135 updated startup message
  Dockerfile
  src/app/Program.cs
Labels: C#, customer feedback

#137 Healthz
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Controllers/HealthzController.cs
  src/app/GlobalSuppressions.cs
  src/app/HealthChecks/JsonResponseWriter.cs
  src/app/KeyVault.Extensions/AuthenticationType.cs
  src/app/KeyVault.Extensions/KeyVaultConnection.cs
  src/app/KeyVault.Extensions/KeyVaultConnectionExtension.cs
  src/app/KeyVault.Extensions/KeyVaultHelper.cs
  src/app/Middleware/RequestLogger/LoggerMiddlewareExtensions.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Middleware/RequestLogger/loggerOptions.cs
  src/app/Middleware/robotsText.cs
  src/app/Middleware/root.cs
  src/app/Middleware/version.cs
  src/app/Program.cs
  src/app/Startup.cs
  src/app/helium.csproj
Labels: C#, customer feedback

#127 Standardize HTTP/400 responses using new JSON format
  TestFiles/bad.json
  TestFiles/e2e.json
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Controllers/ActorsController.cs
  src/app/Controllers/MoviesController.cs
  src/app/Controllers/ParameterValidator.cs
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/DataAccessLayer/idal.cs
  src/app/Extensions/ActorExtensions.cs
  src/app/Extensions/MovieExtensions.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/KeyVault.Extensions/AuthenticationType.cs
  src/app/KeyVault.Extensions/KeyVaultHelper.cs
  src/app/Program.cs
  src/app/QueryParameters.cs
  src/app/ServiceActivator.cs
  src/app/Startup.cs
  src/app/Validation/IdValidation.cs
  src/app/Validation/IntegerRangeValidation.cs
  src/app/Validation/ValidationProblemDetails.cs
  src/app/Validation/ValidationProblemDetailsResult.cs
  src/app/Validation/YearValidation.cs
  src/app/ValidationError.cs
  src/app/helium.csproj
  src/tests/BaseTest.cs
  src/tests/ExtensionTests.cs
  src/tests/RunApp.cs
  src/tests/ValidationTests.cs
  src/tests/tests.csproj
Labels: C#, Enhancement, Refactor

#139 keyvault update
  src/app/CSE.KeyVault/AuthenticationType.cs
  src/app/CSE.KeyVault/KeyVaultConnection.cs
  src/app/CSE.KeyVault/KeyVaultConnectionExtension.cs
  src/app/CSE.KeyVault/KeyVaultHelper.cs
  src/app/CommandLine.cs
  src/app/Program.cs
Labels: C#

#147 Updated scheduled link check to create project cards
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, CI/CD, Documentation

#148 Update libraries / lint
  TestFiles/baseline.json
  TestFiles/e2e.json
  src/app/CSE.KeyVault/KeyVaultConnection.cs
  src/app/CSE.KeyVault/KeyVaultConnectionExtension.cs
  src/app/Controllers/MoviesController.cs
  src/app/HealthChecks/CosmosHealthCheckDetails.cs
  src/app/Validation/ValidationProblemDetailsResult.cs
  src/app/helium.csproj
  src/tests/ExtensionTests.cs
Labels: C#

#150 Issue #146 GitHub Action for .NET docker build on push and schedule
  .github/workflows/codespaces.yml
Labels: CustomerFeedback, DevExperience

#149 Dockerfile containing all tools to run helium setup inside a docker container
  .devcontainer/.bashrc-append
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/azcli-debian.sh
  .devcontainer/library-scripts/docker-debian.sh
  .devcontainer/library-scripts/node-debian.sh
  .devcontainer/post-install.sh
  docs/codespaces/Dockerfile
Labels: C#
