Repository retaildevcrews/helium-csharp, pull requests merged in 2020-08, with the labels that each got.

#109 Renaming MSI references to MI
  README.md
  saveenv.sh
  src/app/CommandLine.cs
  src/app/Constants.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/Program.cs
  src/tests/RunApp.cs
Labels: C#

#110 Updated min and max length values for q parameter
  src/app/wwwroot/swagger/helium.json
Labels: C#

#112 Added PR Closed event handler to ci-cd
  .github/workflows/dockerCI.yaml
Labels: C#

#114 Drain conns
  src/app/Constants.cs
  src/app/Program.cs
Labels: C#

#116 Update ci-cd for PR merged
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/comparison.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/dockerCI.yaml
Labels: C#

#118 updated ci-cd to run webv
  .github/workflows/dockerCI.yaml
Labels: Bug, C#

#119 Changing part key function name
  src/app/DataAccessLayer/dalActors.cs
  src/app/DataAccessLayer/dalMovies.cs
  src/app/Model/Actor.cs
  src/app/Model/Movie.cs
Labels: C#

#120 updated DoD link in github template
  .github/ISSUE_TEMPLATE/dod-review.md
Labels: C#, Documentation
